--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/AdvancedForm
build-by-default: true
branches:
  - master
projects:
  AdvancedForm:
    path: ""
    model: virion
    type: library
...
